### ISSUE TITLE
HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

### ISSUE THREAD

**Issue by youngfreeFJS** [youngfreeFJS/Chrome-GPT#1]
lock selenium version == 4.8.0 and use VPN in China.
but found new err:
AttributeError: 'SeleniumWrapper' object has no attribute 'driver'

seems like selenium version issue? not sure.

**Comment by youngfreeFJS** [comment]
Not related to selenium version

```
(chrome-gpt-py3.9) ➜  Chrome-GPT git:(main) ✗ export https_proxy=http://127.0.0.1:8118;export http_proxy=http://127.0.0.1:8118 && export OPENAI_API_KEY=xxx && python3 -m chromegpt -a auto-gpt -t "Go to Apple and buy apple 14"
Traceback (most recent call last):
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 289, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 438, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 290, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 311, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/urllib3/poolmanager.py", line 533, in urlopen
    return super(ProxyManager, self).urlopen(method, url, redirect=redirect, **kw)
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/urllib3/poolmanager.py", line 374, in urlopen
    response = conn.urlopen(method, url, **kw)
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 289, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/freeyoung/Desktop/codes/github/Chrome-GPT/chromegpt/__main__.py", line 44, in <module>
    main()
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/freeyoung/Desktop/codes/github/Chrome-GPT/chromegpt/__main__.py", line 33, in main
    return run_chromegpt(
  File "/Users/freeyoung/Desktop/codes/github/Chrome-GPT/chromegpt/main.py", line 17, in run_chromegpt
    agent_obj: ChromeGPTAgent = AutoGPTAgent(
  File "/Users/freeyoung/Desktop/codes/github/Chrome-GPT/chromegpt/agent/autogpt/autogpt.py", line 24, in __init__
    self.agent = self._get_autogpt_agent(
  File "/Users/freeyoung/Desktop/codes/github/Chrome-GPT/chromegpt/agent/autogpt/autogpt.py", line 35, in _get_autogpt_agent
    tools = get_agent_tools()
  File "/Users/freeyoung/Desktop/codes/github/Chrome-GPT/chromegpt/agent/utils.py", line 22, in get_agent_tools
    selenium = SeleniumWrapper()
  File "/Users/freeyoung/Desktop/codes/github/Chrome-GPT/chromegpt/tools/selenium.py", line 46, in __init__
    self.driver = webdriver.Chrome(options=chrome_options)
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 84, in __init__
    super().__init__(
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 115, in __init__
    self.quit()
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 242, in quit
    self.service.stop()
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 145, in stop
    self.send_remote_shutdown_command()
  File "/Users/freeyoung/Library/Caches/pypoetry/virtualenvs/chrome-gpt-kSPtB1vH-py3.9/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 124, in send_remote_shutdown_command
    request.urlopen(f"{self.service_url}/shutdown")
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1350, in do_open
    r = h.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 289, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

Exception ignored in: <function SeleniumWrapper.__del__ at 0x119e4cee0>
Traceback (most recent call last):
  File "/Users/freeyoung/Desktop/codes/github/Chrome-GPT/chromegpt/tools/selenium.py", line 51, in __del__
AttributeError: 'SeleniumWrapper' object has no attribute 'driver'
```
